apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: microsvc
  name: microsvc
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: microsvc
  template: 
    metadata: 
      labels: 
        app: microsvc
    spec: 
      containers: 
        - name: microsvc
          image: "atri/test:latest"
          imagePullPolicy: Always
          ports: 
            - 
              containerPort: 31000
          resources: 
            requests: 
              cpu: 125m
              memory: 64Mi
            limits: 
              cpu: 250m
              memory: 128Mi